server: 
  port: 8081

spring:
  application:
    name: movie-main-service

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/  
      
test:
  url: http://noapplicationlocal:8080