server:
  port: 8082


spring:
  application:
    name: movie-info-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/      

api:
  key: 8089cca2f615e2151b0927e3fbf5b2c7